### PR TITLE
Fix misaligned button in UI

### PR DESCRIPTION
**Pull request by joedf**

### CODE REVIEW

**Comment by TAC109** [comment]
You want a GUI change to the 'compress' checkbox'? More details please!

I agree that the parameter name should be changed and I’ll sort this out.

My last 2 enhancements are to allow setting 'Require Administrator', and allow changing the language property.

**Comment by joedf** [comment]
I was thinking about something like this:
ahk2exe_compress_opts2
Great ideas! Also, maybe make it require admin only if it is required. Maybe something like this to check for write permissions:
```ahk
isAdminRunAs_Needed(dir) {
	if A_IsAdmin
		return false
	else {
		tmpfn := Util_TempFile(dir)
		FileAppend,__ASPDM_ADMIN_TEST__,%tmpfn%
		if !(e:=ErrorLevel)
			FileDelete,%tmpfn%
		return e
	}
}
```
Example from: https://github.com/ahkscript/ASPDM/blob/a54bae9763/Local-Client/Package_Lister.ahk#L992-L1002

**Comment by TAC109** [comment]
Compression: Well, I like my one! So unless there are strong reasons to change I’ll leave it as is. (Did you notice how the accelerator key ‘n’ cycles through the options?)

Require Administrator: Not sure what you’re suggesting here? My idea is to allow directive ;@Ahk2Exe-RequireAdmin to set 'RequireAdministrator' in the compiled program's manifest so that when run there is a UAC prompt. There were messages about this in the old thread.

**Comment by joedf** [comment]
No worries, I saw how it cycles after. Very nice!
I got confused, I thought you meant admin rights for ahk2exe itself, my bad :p

**Pull request merged**
